
all_data_names = set(['acceleration limit',
'alarm led',
'backup ready',
'baud rate',
'baud rate (bus)',
'brake delay',
'bus watchdog',
'ccw angle limit',
'ccw compliance margin',
'ccw compliance slope',
'control mode',
'controller state',
'current',
'current limit',
'current offset',
'cw angle limit',
'cw compliance margin',
'cw compliance slope',
'd gain',
'drive mode',
'electronic gearratio denominator',
'electronic gearratio numerator',
'error code',
'error code history 1',
'error code history 15',
'error code history 16',
'error code history 2',
'feedforward 1st gain',
'feedforward 2nd gain',
'firmware version',
'following error threshold',
'goal acceleration',
'goal current',
'goal current lpf frequency',
'goal position',
'goal pwm',
'goal torque',
'goal update delay',
'goal velocity',
'hardware error status',
'homing offset',
'hybrid save',
'i gain',
'id',
'in-position threshold',
'inverter temperature limit',
'led',
'led blue',
'led green',
'led red',
'lock',
'max position limit',
'max torque',
'max voltage limit',
'min position limit',
'min voltage limit',
'model information',
'model number',
'motor temperature limit',
'moving',
'moving speed',
'moving status',
'moving threshold',
'multi turn offset',
'normal excitation voltage',
'operating mode',
'overexcitation time',
'overexcitation voltage',
'p gain',
'position d gain',
'position ff gain',
'position ff lpf time',
'position i gain',
'position limit threshold',
'position p gain',
'position trajectory',
'present current',
'present input voltage',
'present inverter temperature',
'present load',
'present motor temperature',
'present position',
'present pwm',
'present speed',
'present temperature',
'present velocity',
'present velocity lpf frequency',
'present voltage',
'profile acceleration',
'profile acceleration time',
'profile time',
'profile velocity',
'protocol type',
'punch',
'pwm limit',
'pwm offset',
'pwm slope',
'realtime tick',
'registered',
'registered instruction',
'resolution divider',
'return delay time',
'safe stop time',
'secondary id',
'secondary(shadow) id',
'sensed current',
'shutdown',
'startup configuration',
'status return level',
'temperature limit',
'torque ctrl mode enable',
'torque enable',
'torque limit',
'velocity ff gain',
'velocity ff lpf time',
'velocity i gain',
'velocity limit',
'velocity offset',
'velocity p gain',
'velocity trajectory']
)



all_data_properties = set(
['addr_acceleration_limit',
'addr_alarm_led',
'addr_backup_ready',
'addr_baud_rate',
'addr_baud_rate_bus',
'addr_brake_delay',
'addr_bus_watchdog',
'addr_ccw_angle_limit',
'addr_ccw_compliance_margin',
'addr_ccw_compliance_slope',
'addr_control_mode',
'addr_controller_state',
'addr_current',
'addr_current_limit',
'addr_current_offset',
'addr_cw_angle_limit',
'addr_cw_compliance_margin',
'addr_cw_compliance_slope',
'addr_d_gain',
'addr_drive_mode',
'addr_electronic_gearratio_denominator',
'addr_electronic_gearratio_numerator',
'addr_error_code',
'addr_error_code_history_1',
'addr_error_code_history_15',
'addr_error_code_history_16',
'addr_error_code_history_2',
'addr_external_port_data_1',
'addr_external_port_data_2',
'addr_external_port_data_3',
'addr_external_port_data_4',
'addr_external_port_mode_1',
'addr_external_port_mode_2',
'addr_external_port_mode_3',
'addr_external_port_mode_4',
'addr_feedforward_1st_gain',
'addr_feedforward_2nd_gain',
'addr_firmware_version',
'addr_following_error_threshold',
'addr_goal_acceleration',
'addr_goal_current',
'addr_goal_current_lpf_frequency',
'addr_goal_position',
'addr_goal_pwm',
'addr_goal_torque',
'addr_goal_update_delay',
'addr_goal_velocity',
'addr_hardware_error_status',
'addr_homing_offset',
'addr_hybrid_save',
'addr_i_gain',
'addr_id',
'addr_in_position_threshold',
'addr_indirect_address_1',
'addr_indirect_address_127',
'addr_indirect_address_128',
'addr_indirect_address_2',
'addr_indirect_address_256',
'addr_indirect_address_26',
'addr_indirect_address_27',
'addr_indirect_address_28',
'addr_indirect_address_29',
'addr_indirect_address_3',
'addr_indirect_address_30',
'addr_indirect_address_31',
'addr_indirect_address_54',
'addr_indirect_address_55',
'addr_indirect_address_56',
'addr_indirect_data_1',
'addr_indirect_data_127',
'addr_indirect_data_128',
'addr_indirect_data_2',
'addr_indirect_data_256',
'addr_indirect_data_26',
'addr_indirect_data_27',
'addr_indirect_data_28',
'addr_indirect_data_29',
'addr_indirect_data_3',
'addr_indirect_data_30',
'addr_indirect_data_31',
'addr_indirect_data_54',
'addr_indirect_data_55',
'addr_indirect_data_56',
'addr_inverter_temperature_limit',
'addr_led',
'addr_led_blue',
'addr_led_green',
'addr_led_red',
'addr_lock',
'addr_max_position_limit',
'addr_max_torque',
'addr_max_voltage_limit',
'addr_min_position_limit',
'addr_min_voltage_limit',
'addr_model_information',
'addr_model_number',
'addr_motor_temperature_limit',
'addr_moving',
'addr_moving_speed',
'addr_moving_status',
'addr_moving_threshold',
'addr_multi_turn_offset',
'addr_normal_excitation_voltage',
'addr_operating_mode',
'addr_overexcitation_time',
'addr_overexcitation_voltage',
'addr_p_gain',
'addr_position_d_gain',
'addr_position_ff_gain',
'addr_position_ff_lpf_time',
'addr_position_i_gain',
'addr_position_limit_threshold',
'addr_position_p_gain',
'addr_position_trajectory',
'addr_present_current',
'addr_present_input_voltage',
'addr_present_inverter_temperature',
'addr_present_load',
'addr_present_motor_temperature',
'addr_present_position',
'addr_present_pwm',
'addr_present_speed',
'addr_present_temperature',
'addr_present_velocity',
'addr_present_velocity_lpf_frequency',
'addr_present_voltage',
'addr_profile_acceleration',
'addr_profile_acceleration_time',
'addr_profile_time',
'addr_profile_velocity',
'addr_protocol_type',
'addr_punch',
'addr_pwm_limit',
'addr_pwm_offset',
'addr_pwm_slope',
'addr_realtime_tick',
'addr_registered',
'addr_registered_instruction',
'addr_resolution_divider',
'addr_return_delay_time',
'addr_safe_stop_time',
'addr_secondary_id',
'addr_secondary_shadow_id',
'addr_sensed_current',
'addr_shutdown',
'addr_startup_configuration',
'addr_status_return_level',
'addr_temperature_limit',
'addr_torque_ctrl_mode_enable',
'addr_torque_enable',
'addr_torque_limit',
'addr_velocity_ff_gain',
'addr_velocity_ff_lpf_time',
'addr_velocity_i_gain',
'addr_velocity_limit',
'addr_velocity_offset',
'addr_velocity_p_gain',
'addr_velocity_trajectory',
'initial_acceleration_limit',
'initial_alarm_led',
'initial_backup_ready',
'initial_baud_rate',
'initial_baud_rate_bus',
'initial_brake_delay',
'initial_bus_watchdog',
'initial_ccw_angle_limit',
'initial_ccw_compliance_margin',
'initial_ccw_compliance_slope',
'initial_control_mode',
'initial_controller_state',
'initial_current',
'initial_current_limit',
'initial_current_offset',
'initial_cw_angle_limit',
'initial_cw_compliance_margin',
'initial_cw_compliance_slope',
'initial_d_gain',
'initial_drive_mode',
'initial_electronic_gearratio_denominator',
'initial_electronic_gearratio_numerator',
'initial_error_code',
'initial_error_code_history_1',
'initial_error_code_history_15',
'initial_error_code_history_16',
'initial_error_code_history_2',
'initial_external_port_data_1',
'initial_external_port_data_2',
'initial_external_port_data_3',
'initial_external_port_data_4',
'initial_external_port_mode_1',
'initial_external_port_mode_2',
'initial_external_port_mode_3',
'initial_external_port_mode_4',
'initial_feedforward_1st_gain',
'initial_feedforward_2nd_gain',
'initial_firmware_version',
'initial_following_error_threshold',
'initial_goal_acceleration',
'initial_goal_current',
'initial_goal_current_lpf_frequency',
'initial_goal_position',
'initial_goal_pwm',
'initial_goal_torque',
'initial_goal_update_delay',
'initial_goal_velocity',
'initial_hardware_error_status',
'initial_homing_offset',
'initial_hybrid_save',
'initial_i_gain',
'initial_id',
'initial_in_position_threshold',
'initial_indirect_address_1',
'initial_indirect_address_127',
'initial_indirect_address_128',
'initial_indirect_address_2',
'initial_indirect_address_256',
'initial_indirect_address_26',
'initial_indirect_address_27',
'initial_indirect_address_28',
'initial_indirect_address_29',
'initial_indirect_address_3',
'initial_indirect_address_30',
'initial_indirect_address_31',
'initial_indirect_address_54',
'initial_indirect_address_55',
'initial_indirect_address_56',
'initial_indirect_data_1',
'initial_indirect_data_127',
'initial_indirect_data_128',
'initial_indirect_data_2',
'initial_indirect_data_256',
'initial_indirect_data_26',
'initial_indirect_data_27',
'initial_indirect_data_28',
'initial_indirect_data_29',
'initial_indirect_data_3',
'initial_indirect_data_30',
'initial_indirect_data_31',
'initial_indirect_data_54',
'initial_indirect_data_55',
'initial_indirect_data_56',
'initial_inverter_temperature_limit',
'initial_led',
'initial_led_blue',
'initial_led_green',
'initial_led_red',
'initial_lock',
'initial_max_position_limit',
'initial_max_torque',
'initial_max_voltage_limit',
'initial_min_position_limit',
'initial_min_voltage_limit',
'initial_model_information',
'initial_model_number',
'initial_motor_temperature_limit',
'initial_moving',
'initial_moving_speed',
'initial_moving_status',
'initial_moving_threshold',
'initial_multi_turn_offset',
'initial_normal_excitation_voltage',
'initial_operating_mode',
'initial_overexcitation_time',
'initial_overexcitation_voltage',
'initial_p_gain',
'initial_position_d_gain',
'initial_position_ff_gain',
'initial_position_ff_lpf_time',
'initial_position_i_gain',
'initial_position_limit_threshold',
'initial_position_p_gain',
'initial_position_trajectory',
'initial_present_current',
'initial_present_input_voltage',
'initial_present_inverter_temperature',
'initial_present_load',
'initial_present_motor_temperature',
'initial_present_position',
'initial_present_pwm',
'initial_present_speed',
'initial_present_temperature',
'initial_present_velocity',
'initial_present_velocity_lpf_frequency',
'initial_present_voltage',
'initial_profile_acceleration',
'initial_profile_acceleration_time',
'initial_profile_time',
'initial_profile_velocity',
'initial_protocol_type',
'initial_punch',
'initial_pwm_limit',
'initial_pwm_offset',
'initial_pwm_slope',
'initial_realtime_tick',
'initial_registered',
'initial_registered_instruction',
'initial_resolution_divider',
'initial_return_delay_time',
'initial_safe_stop_time',
'initial_secondary_id',
'initial_secondary_shadow_id',
'initial_sensed_current',
'initial_shutdown',
'initial_startup_configuration',
'initial_status_return_level',
'initial_temperature_limit',
'initial_torque_ctrl_mode_enable',
'initial_torque_enable',
'initial_torque_limit',
'initial_velocity_ff_gain',
'initial_velocity_ff_lpf_time',
'initial_velocity_i_gain',
'initial_velocity_limit',
'initial_velocity_offset',
'initial_velocity_p_gain',
'initial_velocity_trajectory',
'len_acceleration_limit',
'len_alarm_led',
'len_backup_ready',
'len_baud_rate',
'len_baud_rate_bus',
'len_brake_delay',
'len_bus_watchdog',
'len_ccw_angle_limit',
'len_ccw_compliance_margin',
'len_ccw_compliance_slope',
'len_control_mode',
'len_controller_state',
'len_current',
'len_current_limit',
'len_current_offset',
'len_cw_angle_limit',
'len_cw_compliance_margin',
'len_cw_compliance_slope',
'len_d_gain',
'len_drive_mode',
'len_electronic_gearratio_denominator',
'len_electronic_gearratio_numerator',
'len_error_code',
'len_error_code_history_1',
'len_error_code_history_15',
'len_error_code_history_16',
'len_error_code_history_2',
'len_external_port_data_1',
'len_external_port_data_2',
'len_external_port_data_3',
'len_external_port_data_4',
'len_external_port_mode_1',
'len_external_port_mode_2',
'len_external_port_mode_3',
'len_external_port_mode_4',
'len_feedforward_1st_gain',
'len_feedforward_2nd_gain',
'len_firmware_version',
'len_following_error_threshold',
'len_goal_acceleration',
'len_goal_current',
'len_goal_current_lpf_frequency',
'len_goal_position',
'len_goal_pwm',
'len_goal_torque',
'len_goal_update_delay',
'len_goal_velocity',
'len_hardware_error_status',
'len_homing_offset',
'len_hybrid_save',
'len_i_gain',
'len_id',
'len_in_position_threshold',
'len_indirect_address_1',
'len_indirect_address_127',
'len_indirect_address_128',
'len_indirect_address_2',
'len_indirect_address_256',
'len_indirect_address_26',
'len_indirect_address_27',
'len_indirect_address_28',
'len_indirect_address_29',
'len_indirect_address_3',
'len_indirect_address_30',
'len_indirect_address_31',
'len_indirect_address_54',
'len_indirect_address_55',
'len_indirect_address_56',
'len_indirect_data_1',
'len_indirect_data_127',
'len_indirect_data_128',
'len_indirect_data_2',
'len_indirect_data_256',
'len_indirect_data_26',
'len_indirect_data_27',
'len_indirect_data_28',
'len_indirect_data_29',
'len_indirect_data_3',
'len_indirect_data_30',
'len_indirect_data_31',
'len_indirect_data_54',
'len_indirect_data_55',
'len_indirect_data_56',
'len_inverter_temperature_limit',
'len_led',
'len_led_blue',
'len_led_green',
'len_led_red',
'len_lock',
'len_max_position_limit',
'len_max_torque',
'len_max_voltage_limit',
'len_min_position_limit',
'len_min_voltage_limit',
'len_model_information',
'len_model_number',
'len_motor_temperature_limit',
'len_moving',
'len_moving_speed',
'len_moving_status',
'len_moving_threshold',
'len_multi_turn_offset',
'len_normal_excitation_voltage',
'len_operating_mode',
'len_overexcitation_time',
'len_overexcitation_voltage',
'len_p_gain',
'len_position_d_gain',
'len_position_ff_gain',
'len_position_ff_lpf_time',
'len_position_i_gain',
'len_position_limit_threshold',
'len_position_p_gain',
'len_position_trajectory',
'len_present_current',
'len_present_input_voltage',
'len_present_inverter_temperature',
'len_present_load',
'len_present_motor_temperature',
'len_present_position',
'len_present_pwm',
'len_present_speed',
'len_present_temperature',
'len_present_velocity',
'len_present_velocity_lpf_frequency',
'len_present_voltage',
'len_profile_acceleration',
'len_profile_acceleration_time',
'len_profile_time',
'len_profile_velocity',
'len_protocol_type',
'len_punch',
'len_pwm_limit',
'len_pwm_offset',
'len_pwm_slope',
'len_realtime_tick',
'len_registered',
'len_registered_instruction',
'len_resolution_divider',
'len_return_delay_time',
'len_safe_stop_time',
'len_secondary_id',
'len_secondary_shadow_id',
'len_sensed_current',
'len_shutdown',
'len_startup_configuration',
'len_status_return_level',
'len_temperature_limit',
'len_torque_ctrl_mode_enable',
'len_torque_enable',
'len_torque_limit',
'len_velocity_ff_gain',
'len_velocity_ff_lpf_time',
'len_velocity_i_gain',
'len_velocity_limit',
'len_velocity_offset',
'len_velocity_p_gain',
'len_velocity_trajectory']
)